### ISSUE TITLE
Feature being enabled even with cargo run --no-default-features

### ISSUE THREAD

**Issue by kartva** [DesmondWillowbrook/cargo-optional-features-for-testing-and-examples#1]
The `add_two` function is still being activated in the produced binary when running `cargo run --no-default-features`.﻿

**Comment by sander2** [comment]
Do you have any idea if this is solved by [Features 2.0](https://github.com/rust-lang/cargo/issues/8088)?

**Comment by kartva** [comment]
I don't think so. The only reason the package compiles at all is due to Cargo's indifference at cyclical dependencies. Earlier, this would've thrown an error. (See: [this PR to Cargo](https://github.com/rust-lang/cargo/pull/3921#issuecomment-297421636))
